### ISSUE TITLE
Extra whitespace between chinese characters and alphabet

### ISSUE THREAD

**Issue by weihanglo** [chenesan/flying-days#1]
For readability, I wonder that we could insert [pangu space](https://github.com/vinta/pangu.js) between CJK and half-width characters.

By the way, your notes are really informative. Keep going!

**Comment by chenesan** [comment]
That's Interesting! I think I will try pangu.js in this weekend.

And, thanks for your admiration. Maybe you can try it, too?

**Comment by weihanglo** [comment]
I have already created [a section](https://weihanglo.tw/tips/) on my personal Github page. However, there is nothing though....
